#!/usr/bin/env python3
"""Render generated reference pages for the teradata-vantage plugin.

Inputs (single sources of truth):
  scripts/data/error_codes.yaml  ->  skills/teradata-sql/references/error-codes.md
  scripts/data/mcp_tools.yaml    ->  skills/setup/references/tool-inventory.md

Usage:
  python3 scripts/render_references.py            # write both files (idempotent)
  python3 scripts/render_references.py --check    # exit 1 if either rendered file differs from disk
  python3 scripts/render_references.py --print    # print both renderings to stdout, write nothing

Python 3 standard library + PyYAML. No network, no database. Output is deterministic: identical input
produces byte-identical output, so a --check run in CI catches a hand edit of a generated file.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.stderr.write("render_references.py: PyYAML is required (pip install pyyaml)\n")
    sys.exit(2)

PLUGIN_ROOT = Path(__file__).resolve().parent.parent
ERROR_CODES_YAML = PLUGIN_ROOT / "scripts" / "data" / "error_codes.yaml"
MCP_TOOLS_YAML = PLUGIN_ROOT / "scripts" / "data" / "mcp_tools.yaml"
ERROR_CODES_MD = PLUGIN_ROOT / "skills" / "teradata-sql" / "references" / "error-codes.md"
TOOL_INVENTORY_MD = PLUGIN_ROOT / "skills" / "setup" / "references" / "tool-inventory.md"

GENERATED_BANNER = "<!-- GENERATED by scripts/render_references.py from {source}. Do not edit by hand. -->"

AREA_ORDER = ["dialect", "space", "security", "nos", "otf", "tdvs", "connection", "recovery"]
AREA_TITLES = {
    "dialect": "SQL dialect, objects and types",
    "space": "Space and capacity",
    "security": "Rights, ownership and proxy connections",
    "nos": "Native Object Store (NOS) and authorizations",
    "otf": "Open table format (Iceberg) and datalakes",
    "tdvs": "Enterprise Vector Store",
    "connection": "Connection and transport",
    "recovery": "Host-level recovery signatures",
}
VALID_AREAS = set(AREA_ORDER)
REQUIRED_KEYS = {"code", "message_fragment", "area", "means", "action", "skill", "confirmed"}


# ----------------------------------------------------------------------------- helpers
def _cell(text: str) -> str:
    """Escape a value for a Markdown table cell."""
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def _load_yaml(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    if not isinstance(data, dict):
        raise ValueError(f"{path}: top level must be a mapping")
    return data


def _rel(path: Path) -> str:
    return path.relative_to(PLUGIN_ROOT).as_posix()


# ----------------------------------------------------------------------------- error codes
def validate_error_codes(errors: list[dict]) -> None:
    seen: set[int] = set()
    for item in errors:
        missing = REQUIRED_KEYS - set(item)
        if missing:
            raise ValueError(f"error_codes.yaml: entry {item.get('code')!r} missing keys {sorted(missing)}")
        code = item["code"]
        if not isinstance(code, int):
            raise ValueError(f"error_codes.yaml: code {code!r} must be an int")
        if code in seen:
            raise ValueError(f"error_codes.yaml: duplicate code {code}")
        seen.add(code)
        if item["area"] not in VALID_AREAS:
            raise ValueError(f"error_codes.yaml: code {code} has unknown area {item['area']!r}")
        if not isinstance(item["confirmed"], bool):
            raise ValueError(f"error_codes.yaml: code {code} confirmed must be true/false")
        skill_dir = PLUGIN_ROOT / "skills" / str(item["skill"])
        # The skill directory may not exist yet while the plugin is being assembled; warn, do not fail.
        if not skill_dir.is_dir():
            sys.stderr.write(f"render_references.py: note: skills/{item['skill']} not present yet (code {code})\n")


def _error_table(rows: list[dict]) -> list[str]:
    out = [
        "| Code | Message fragment | What it actually means | Do this | Skill |",
        "|---|---|---|---|---|",
    ]
    for e in sorted(rows, key=lambda r: r["code"]):
        out.append(
            "| {code} | `{frag}` | {means} | {action} | `{skill}` |".format(
                code=e["code"],
                frag=_cell(e["message_fragment"]).replace("`", "'"),
                means=_cell(e["means"]),
                action=_cell(e["action"]),
                skill=_cell(e["skill"]),
            )
        )
    return out


def render_error_codes(data: dict) -> str:
    errors = data.get("errors")
    if not isinstance(errors, list) or not errors:
        raise ValueError("error_codes.yaml: expected a non-empty list under key 'errors'")
    validate_error_codes(errors)

    confirmed = [e for e in errors if e["confirmed"]]
    unconfirmed = [e for e in errors if not e["confirmed"]]

    lines: list[str] = []
    lines.append("# Teradata error codes — what each message actually means, and what to do")
    lines.append("")
    lines.append(GENERATED_BANNER.format(source=_rel(ERROR_CODES_YAML)))
    lines.append("")
    lines.append(
        "Purpose: the error-code companion to `teradata-sql`; look a code up here before changing a "
        "statement, and quote the code and message verbatim when reporting to the user."
    )
    lines.append("")
    lines.append(
        f"{len(confirmed)} confirmed codes and {len(unconfirmed)} reported-but-unverified codes, "
        f"from `{_rel(ERROR_CODES_YAML)}`. The same file drives the plugin's PostToolUse coaching note, "
        "so the two never disagree. Text authored from Teradata documentation is marked as such in the "
        "source file (from Teradata documentation; verify against your release)."
    )
    lines.append("")
    lines.append("How to read a Teradata error:")
    lines.append("")
    lines.append("- The code is stable across releases; the message text is what tells you which case you hit.")
    lines.append("- Fix exactly the named defect, re-run once, and stop after two retries.")
    lines.append(
        "- On 5628 / 3810 / 3807, discover the real name with `base_tableDDL` or `base_tableList` in the "
        "same turn before retrying."
    )
    lines.append("- Messages that read like syntax (3541) or like a missing object (3802 after a failed CREATE) often mean space.")
    lines.append("")
    lines.append("## Confirmed codes")
    lines.append("")
    lines.append("Message text verified against Teradata documentation or a real message captured on a live system.")
    for area in AREA_ORDER:
        rows = [e for e in confirmed if e["area"] == area]
        if not rows:
            continue
        lines.append("")
        lines.append(f"### {AREA_TITLES[area]}")
        lines.append("")
        lines.extend(_error_table(rows))
    lines.append("")
    lines.append("## Reported but unverified")
    lines.append("")
    if unconfirmed:
        lines.append(
            "These codes were observed on live systems, but the message text below was not verified "
            "against Teradata documentation or a captured message. Treat the fragment as a hint, read the "
            "real message when you meet it, and verify against your release."
        )
        for area in AREA_ORDER:
            rows = [e for e in unconfirmed if e["area"] == area]
            if not rows:
                continue
            lines.append("")
            lines.append(f"### {AREA_TITLES[area]} (unverified)")
            lines.append("")
            lines.extend(_error_table(rows))
    else:
        lines.append("None.")
    lines.append("")
    lines.append("## Index by code")
    lines.append("")
    index = ", ".join(
        f"{e['code']}{'' if e['confirmed'] else '*'}" for e in sorted(errors, key=lambda r: r["code"])
    )
    lines.append(index)
    lines.append("")
    lines.append("`*` = unverified.")
    lines.append("")
    return "\n".join(lines)


# ----------------------------------------------------------------------------- tool inventory
def render_tool_inventory(data: dict) -> str:
    prefix = str(data.get("tool_prefix", ""))
    groups = data.get("groups") or {}
    if not isinstance(groups, dict) or not groups:
        raise ValueError("mcp_tools.yaml: expected a mapping under key 'groups'")

    total_tools = sum(len(g.get("tools") or []) for g in groups.values())
    total_prompts = sum(len(g.get("prompts") or []) for g in groups.values())
    # Resources: either a flat `resources` list, or the split `resources_live` (always registered) +
    # `resources_when_glossary_defined` (registered only when CONFIG_DIR defines glossary terms).
    resources_always = list(data.get("resources") or []) + list(data.get("resources_live") or [])
    resources_glossary = list(data.get("resources_when_glossary_defined") or [])
    resources = resources_always + resources_glossary
    guarded = data.get("guarded_read_tools") or []
    destructive = data.get("destructive_tools") or []
    pd_tools = data.get("progressive_disclosure_tools") or []
    captured_live = bool(data.get("captured_live", False))

    lines: list[str] = []
    lines.append("# Tool inventory — the bundled Teradata MCP server as this plugin exposes it")
    lines.append("")
    lines.append(GENERATED_BANNER.format(source=_rel(MCP_TOOLS_YAML)))
    lines.append("")
    lines.append(
        "Purpose: the exact tool, prompt and resource names the `teradata` server registers, grouped as "
        "upstream groups them, so a skill or agent can name a tool without guessing."
    )
    lines.append("")
    lines.append(f"- Package: `{data.get('package', '')}` version `{data.get('verified_version', '')}`")
    lines.append(f"- Wheel sha256: `{data.get('wheel_sha256', '')}`")
    lines.append(f"- Server key in `.mcp.json`: `{data.get('server_key', '')}`")
    lines.append(f"- Full tool-name prefix: `{prefix}<tool>`")
    lines.append(f"- Groups: {len(groups)}; tools listed: {total_tools}; prompts listed: {total_prompts}; resources: {len(resources)}")
    if data.get("live_core_tool_count") is not None:
        lines.append(
            f"- Tools registered by a core install (no extras, default profile) at capture time: "
            f"{data['live_core_tool_count']}"
        )
    lines.append(
        "- Inventory source: "
        + ("captured from a live `tools/list` + `prompts/list` + `resources/list` against the vendored wheel; groups "
           "that register only with extras or extra environment are listed from the upstream source."
           if captured_live
           else "seeded from the upstream source; not yet captured from a live `tools/list`. Profiles and installed "
                "extras change what a given session actually sees — confirm with `/mcp`.")
    )
    if data.get("longest_namespaced_tool_name_chars") is not None:
        lines.append(
            f"- Longest fully namespaced tool name: {data['longest_namespaced_tool_name_chars']} characters"
            + (f" — {_cell(data['notes'])}" if data.get("notes") else "")
        )
    lines.append("")
    lines.append("Which groups load is decided by the server profile (`config/profiles.yml`; default `tv_all`) and by the "
                 "optional extras installed with the local server. A tool that is not loaded is not callable, however it is named here.")
    lines.append("")
    lines.append("## Groups")
    lines.append("")
    lines.append("| Group | Extra | Tools | Prompts | Notes |")
    lines.append("|---|---|---|---|---|")
    for name, g in groups.items():
        tools = g.get("tools") or []
        prompts = g.get("prompts") or []
        extra = g.get("extra")
        lines.append(
            "| `{name}` | {extra} | {ntools} | {nprompts} | {notes} |".format(
                name=name,
                extra=f"`{extra}`" if extra else "core",
                ntools=len(tools),
                nprompts=len(prompts),
                notes=_cell(g.get("notes") or ""),
            )
        )
    for name, g in groups.items():
        tools = g.get("tools") or []
        prompts = g.get("prompts") or []
        lines.append("")
        lines.append(f"### `{name}`")
        lines.append("")
        extra = g.get("extra")
        if extra:
            lines.append(f"Requires the `{extra}` extra (`/teradata-vantage:setup install` with extras, or `TERADATA_MCP_EXTRAS`).")
            lines.append("")
        if g.get("notes"):
            lines.append(str(g["notes"]).strip())
            lines.append("")
        if tools:
            lines.append("Tools:")
            lines.append("")
            for t in tools:
                flags = []
                if t in guarded:
                    flags.append("read-only guard")
                if t in destructive:
                    flags.append("approval prompt")
                if t in pd_tools:
                    flags.append("progressive-disclosure")
                suffix = f" — {', '.join(flags)}" if flags else ""
                lines.append(f"- `{prefix}{t}`{suffix}")
        else:
            lines.append("Tools: none registered statically (see notes).")
        if prompts:
            lines.append("")
            lines.append("Prompts (surface as slash commands, as exposed by `/mcp`):")
            lines.append("")
            for p in prompts:
                lines.append(f"- `{p}`")
    lines.append("")
    lines.append("## Resources")
    lines.append("")
    lines.append("Read with `@` in the prompt (as exposed by `/mcp`).")
    lines.append("")
    if resources_always:
        for r in resources_always:
            lines.append(f"- `{r}`")
    else:
        lines.append("- none registered unconditionally")
    if resources_glossary:
        lines.append("")
        lines.append(
            "Registered only when the server's `CONFIG_DIR` defines glossary terms "
            "(see `config/example_domain_objects.yml.example`):"
        )
        lines.append("")
        for r in resources_glossary:
            lines.append(f"- `{r}`")
    lines.append("")
    lines.append("## Safety classification")
    lines.append("")
    lines.append(
        "Held read-only by a PreToolUse hook (ONE statement, starting SELECT/WITH/EXPLAIN/SHOW/HELP; a blocked "
        "verb anywhere else denies the call, except after a leading EXPLAIN, which returns a plan and executes "
        "nothing — so EXPLAIN DELETE / INSERT / UPDATE / MERGE are allowed; "
        "`TERADATA_SQL_GUARD_MODE=audit` logs instead of denying):"
    )
    lines.append("")
    for t in guarded:
        lines.append(f"- `{prefix}{t}`")
    lines.append("")
    lines.append(
        "Raise an approval prompt before running. The SQL-executing tools prompt only when the statement is destructive — "
        "DELETE, DROP, TRUNCATE, INSERT, UPDATE, MERGE, ALTER, MODIFY, RENAME, REPLACE (VIEW/MACRO/PROCEDURE/…), GIVE, CREATE DATABASE/USER, GRANT, REVOKE, ABORT SESSION "
        "(a statement that is only DROP FOREIGN TABLE is exempt as metadata-only, and that exemption is applied per "
        "STATEMENT, never to a whole compound call); the vector-store, backup and pipeline tools always prompt; "
        "`TERADATA_ALLOW_WRITES=0` denies all writes:"
    )
    lines.append("")
    for t in destructive:
        lines.append(f"- `{prefix}{t}`")
    lines.append("")
    if pd_tools:
        lines.append(
            "When the server runs with `PROGRESSIVE_DISCLOSURE=true`, most tools are reached through these instead, "
            "and the hooks classify `execute_tool` calls by the inner `tool_name`:"
        )
        lines.append("")
        for t in pd_tools:
            lines.append(f"- `{prefix}{t}`")
        lines.append("")
    lines.append(
        "These guards are mistake-prevention on the analyst tools, not a security boundary; the database's own "
        "rights model is the boundary."
    )
    lines.append("")
    return "\n".join(lines)


# ----------------------------------------------------------------------------- main
def _write_or_check(path: Path, content: str, check: bool) -> bool:
    """Return True when the on-disk file matches (check) or was written (write)."""
    if check:
        if not path.exists():
            sys.stderr.write(f"render_references.py: MISSING {_rel(path)}\n")
            return False
        current = path.read_text(encoding="utf-8")
        if current != content:
            sys.stderr.write(f"render_references.py: DRIFT {_rel(path)} (re-run without --check)\n")
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        sys.stderr.write(f"render_references.py: unchanged {_rel(path)}\n")
        return True
    path.write_text(content, encoding="utf-8")
    sys.stderr.write(f"render_references.py: wrote {_rel(path)} ({len(content.encode('utf-8'))} bytes)\n")
    return True


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if rendered output differs from disk")
    ap.add_argument("--print", dest="print_only", action="store_true", help="print renderings, write nothing")
    args = ap.parse_args(argv)

    error_md = render_error_codes(_load_yaml(ERROR_CODES_YAML))
    tools_md = render_tool_inventory(_load_yaml(MCP_TOOLS_YAML))

    if args.print_only:
        sys.stdout.write(error_md)
        sys.stdout.write("\n\n" + "=" * 78 + "\n\n")
        sys.stdout.write(tools_md)
        return 0

    ok = True
    ok &= _write_or_check(ERROR_CODES_MD, error_md, args.check)
    ok &= _write_or_check(TOOL_INVENTORY_MD, tools_md, args.check)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
